/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AddEdgeDelta : Insert an edge.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddEdgeDelta {
    #[serde(rename = "edge")]
    pub edge: Box<models::Edge>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl AddEdgeDelta {
    /// Insert an edge.
    pub fn new(edge: models::Edge, r#type: Type) -> AddEdgeDelta {
        AddEdgeDelta {
            edge: Box::new(edge),
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "add_edge")]
    AddEdge,
}

impl Default for Type {
    fn default() -> Type {
        Self::AddEdge
    }
}

