/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AddNodeDelta : Insert a node.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddNodeDelta {
    #[serde(rename = "node")]
    pub node: Box<models::Node>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl AddNodeDelta {
    /// Insert a node.
    pub fn new(node: models::Node, r#type: Type) -> AddNodeDelta {
        AddNodeDelta {
            node: Box::new(node),
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "add_node")]
    AddNode,
}

impl Default for Type {
    fn default() -> Type {
        Self::AddNode
    }
}

