/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AnchorRef : Where a decision is anchored. ``id`` is a free-text reference whose meaning depends on ``type`` (a node/boundary UUID, an error payload key, or absent for a project-level decision).  ``type`` is an OPEN set, published as a plain string, for exactly the reason ``Finding.code`` is — see that model. The anchor vocabulary is server-owned and grows additively as new things become anchorable, so a consumer must tolerate a ``type`` it does not recognize.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnchorRef {
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<String>,
    /// What the decision is anchored to. Known values: `boundary`, `node`, `error_payload`, `project`. **This set is open and grows additively** — treat an unrecognized type as an opaque string and render it; do not fail on it.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl AnchorRef {
    /// Where a decision is anchored. ``id`` is a free-text reference whose meaning depends on ``type`` (a node/boundary UUID, an error payload key, or absent for a project-level decision).  ``type`` is an OPEN set, published as a plain string, for exactly the reason ``Finding.code`` is — see that model. The anchor vocabulary is server-owned and grows additively as new things become anchorable, so a consumer must tolerate a ``type`` it does not recognize.
    pub fn new(id: Option<String>, r#type: String) -> AnchorRef {
        AnchorRef {
            id,
            r#type,
        }
    }
}

