/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApplyBranchDeltasV1BranchesBranchIdDeltasPost409ResponseDetail {
    VersionConflictBody(Box<models::VersionConflictBody>),
    BranchNotActiveBody(Box<models::BranchNotActiveBody>),
}

impl Default for ApplyBranchDeltasV1BranchesBranchIdDeltasPost409ResponseDetail {
    fn default() -> Self {
        Self::VersionConflictBody(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "branch_not_active")]
    BranchNotActive,
}

impl Default for Error {
    fn default() -> Error {
        Self::BranchNotActive
    }
}

