/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AppliedDecisionFilters : The narrowing the server ACTUALLY applied, echoed back.  Not a copy of the query string: ``owner_layer`` omitted means \"your whole altitude membership\", ``state`` omitted means \"every settled state\", and neither is knowable client-side. Without the echo an empty page is indistinguishable from \"this project has no decisions\", which is a different fact and sends the caller looking in the wrong place.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppliedDecisionFilters {
    #[serde(rename = "owner_layer")]
    pub owner_layer: Vec<String>,
    #[serde(rename = "state")]
    pub state: Vec<String>,
}

impl AppliedDecisionFilters {
    /// The narrowing the server ACTUALLY applied, echoed back.  Not a copy of the query string: ``owner_layer`` omitted means \"your whole altitude membership\", ``state`` omitted means \"every settled state\", and neither is knowable client-side. Without the echo an empty page is indistinguishable from \"this project has no decisions\", which is a different fact and sends the caller looking in the wrong place.
    pub fn new(owner_layer: Vec<String>, state: Vec<String>) -> AppliedDecisionFilters {
        AppliedDecisionFilters {
            owner_layer,
            state,
        }
    }
}

