/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplyBranchDeltasV1BranchesBranchIdDeltasPost409Response {
    #[serde(rename = "detail")]
    pub detail: Box<models::ApplyBranchDeltasV1BranchesBranchIdDeltasPost409ResponseDetail>,
}

impl ApplyBranchDeltasV1BranchesBranchIdDeltasPost409Response {
    pub fn new(detail: models::ApplyBranchDeltasV1BranchesBranchIdDeltasPost409ResponseDetail) -> ApplyBranchDeltasV1BranchesBranchIdDeltasPost409Response {
        ApplyBranchDeltasV1BranchesBranchIdDeltasPost409Response {
            detail: Box::new(detail),
        }
    }
}

