/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BoundaryResponse {
    #[serde(rename = "boundary")]
    pub boundary: Box<models::WireNode>,
    #[serde(rename = "branch")]
    pub branch: Box<models::BranchRef>,
    #[serde(rename = "children")]
    pub children: Vec<models::WireNode>,
    #[serde(rename = "edges")]
    pub edges: Vec<models::WireEdge>,
    #[serde(rename = "project_id")]
    pub project_id: uuid::Uuid,
    #[serde(rename = "version")]
    pub version: String,
}

impl BoundaryResponse {
    pub fn new(boundary: models::WireNode, branch: models::BranchRef, children: Vec<models::WireNode>, edges: Vec<models::WireEdge>, project_id: uuid::Uuid, version: String) -> BoundaryResponse {
        BoundaryResponse {
            boundary: Box::new(boundary),
            branch: Box::new(branch),
            children,
            edges,
            project_id,
            version,
        }
    }
}

