/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BranchMeta {
    #[serde(rename = "base_main_version")]
    pub base_main_version: i32,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "is_main")]
    pub is_main: bool,
    #[serde(rename = "last_active_at")]
    pub last_active_at: String,
    #[serde(rename = "merged_at", deserialize_with = "Option::deserialize")]
    pub merged_at: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "owner_id", deserialize_with = "Option::deserialize")]
    pub owner_id: Option<uuid::Uuid>,
    #[serde(rename = "project_id")]
    pub project_id: uuid::Uuid,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "version")]
    pub version: i32,
}

impl BranchMeta {
    pub fn new(base_main_version: i32, created_at: String, id: uuid::Uuid, is_main: bool, last_active_at: String, merged_at: Option<String>, name: String, owner_id: Option<uuid::Uuid>, project_id: uuid::Uuid, status: String, version: i32) -> BranchMeta {
        BranchMeta {
            base_main_version,
            created_at,
            id,
            is_main,
            last_active_at,
            merged_at,
            name,
            owner_id,
            project_id,
            status,
            version,
        }
    }
}

