/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DecisionsListResponse : One page of decisions for one project.  ``has_more`` is explicit rather than inferred from ``len(decisions) == limit``: a page that happens to end exactly on the boundary is indistinguishable from a full one, and a caller that guesses wrong either stops early or pages forever.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecisionsListResponse {
    #[serde(rename = "decisions")]
    pub decisions: Vec<models::DecisionOut>,
    #[serde(rename = "filters")]
    pub filters: Box<models::AppliedDecisionFilters>,
    #[serde(rename = "has_more")]
    pub has_more: bool,
    #[serde(rename = "limit")]
    pub limit: i32,
    #[serde(rename = "offset")]
    pub offset: i32,
    #[serde(rename = "project_id")]
    pub project_id: uuid::Uuid,
    #[serde(rename = "version")]
    pub version: String,
}

impl DecisionsListResponse {
    /// One page of decisions for one project.  ``has_more`` is explicit rather than inferred from ``len(decisions) == limit``: a page that happens to end exactly on the boundary is indistinguishable from a full one, and a caller that guesses wrong either stops early or pages forever.
    pub fn new(
        decisions: Vec<models::DecisionOut>,
        filters: models::AppliedDecisionFilters,
        has_more: bool,
        limit: i32,
        offset: i32,
        project_id: uuid::Uuid,
        version: String,
    ) -> DecisionsListResponse {
        DecisionsListResponse {
            decisions,
            filters: Box::new(filters),
            has_more,
            limit,
            offset,
            project_id,
            version,
        }
    }
}
