/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DecisionOut : A decision as the /v1 surface serves it.  **Deliberately narrower than the in-app serializer.** The fields it omits are omitted for a reason, and the omission is the mitigation — adding one back is a disclosure decision, not a serializer tweak:    * ``history`` — the append-only audit trail, which names the actor     of every transition. Accountability data for humans in the app,     not context for an agent.   * ``assignee_user_id`` — a user id, same reasoning.   * ``draft_ids`` / ``originating_interview_ref`` — pointers into     interview transcripts, which are the candid text itself.   * ``interview_session`` — the transcript. Never.   * ``snoozed_until`` — in-app queue mechanics with no meaning to an     external caller.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecisionOut {
    #[serde(rename = "anchor_ref")]
    pub anchor_ref: Box<models::AnchorRef>,
    #[serde(rename = "annotations", deserialize_with = "Option::deserialize")]
    pub annotations: Option<String>,
    #[serde(rename = "capture_text")]
    pub capture_text: String,
    #[serde(rename = "captured_at")]
    pub captured_at: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "owner_layer")]
    pub owner_layer: String,
    #[serde(rename = "parent_decision_id", deserialize_with = "Option::deserialize")]
    pub parent_decision_id: Option<uuid::Uuid>,
    #[serde(rename = "project_id")]
    pub project_id: uuid::Uuid,
    #[serde(rename = "resulting_node_ids")]
    pub resulting_node_ids: Vec<uuid::Uuid>,
    #[serde(rename = "source_layer")]
    pub source_layer: String,
    #[serde(rename = "state")]
    pub state: String,
}

impl DecisionOut {
    /// A decision as the /v1 surface serves it.  **Deliberately narrower than the in-app serializer.** The fields it omits are omitted for a reason, and the omission is the mitigation — adding one back is a disclosure decision, not a serializer tweak:    * ``history`` — the append-only audit trail, which names the actor     of every transition. Accountability data for humans in the app,     not context for an agent.   * ``assignee_user_id`` — a user id, same reasoning.   * ``draft_ids`` / ``originating_interview_ref`` — pointers into     interview transcripts, which are the candid text itself.   * ``interview_session`` — the transcript. Never.   * ``snoozed_until`` — in-app queue mechanics with no meaning to an     external caller.
    pub fn new(anchor_ref: models::AnchorRef, annotations: Option<String>, capture_text: String, captured_at: String, id: uuid::Uuid, owner_layer: String, parent_decision_id: Option<uuid::Uuid>, project_id: uuid::Uuid, resulting_node_ids: Vec<uuid::Uuid>, source_layer: String, state: String) -> DecisionOut {
        DecisionOut {
            anchor_ref: Box::new(anchor_ref),
            annotations,
            capture_text,
            captured_at,
            id,
            owner_layer,
            parent_decision_id,
            project_id,
            resulting_node_ids,
            source_layer,
            state,
        }
    }
}

