/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteNodeDelta : Cascade-delete a node and its descendant subtree.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteNodeDelta {
    #[serde(rename = "node_id")]
    pub node_id: uuid::Uuid,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl DeleteNodeDelta {
    /// Cascade-delete a node and its descendant subtree.
    pub fn new(node_id: uuid::Uuid, r#type: Type) -> DeleteNodeDelta {
        DeleteNodeDelta {
            node_id,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "delete_node")]
    DeleteNode,
}

impl Default for Type {
    fn default() -> Type {
        Self::DeleteNode
    }
}

