/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeltaApplyResponse {
    #[serde(rename = "applied")]
    pub applied: bool,
    #[serde(rename = "branch")]
    pub branch: Box<models::BranchRef>,
    #[serde(rename = "delta_count")]
    pub delta_count: i32,
    #[serde(rename = "positions_applied", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub positions_applied: Option<Option<i32>>,
    #[serde(rename = "project_id")]
    pub project_id: uuid::Uuid,
    #[serde(rename = "version")]
    pub version: String,
}

impl DeltaApplyResponse {
    pub fn new(applied: bool, branch: models::BranchRef, delta_count: i32, project_id: uuid::Uuid, version: String) -> DeltaApplyResponse {
        DeltaApplyResponse {
            applied,
            branch: Box::new(branch),
            delta_count,
            positions_applied: None,
            project_id,
            version,
        }
    }
}

