/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeltaFieldErrorBody : The 7-key per-delta envelope (always all keys present) the frontend auto-recovery consumes. Shared by every 422 delta error; `error` discriminates the cause.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeltaFieldErrorBody {
    #[serde(rename = "delta_ordinal", deserialize_with = "Option::deserialize")]
    pub delta_ordinal: Option<i32>,
    #[serde(rename = "delta_type", deserialize_with = "Option::deserialize")]
    pub delta_type: Option<String>,
    #[serde(rename = "error")]
    pub error: Error,
    #[serde(rename = "field", deserialize_with = "Option::deserialize")]
    pub field: Option<String>,
    #[serde(rename = "reason", deserialize_with = "Option::deserialize")]
    pub reason: Option<String>,
    #[serde(rename = "recoverable")]
    pub recoverable: bool,
    #[serde(rename = "recovery_hint", deserialize_with = "Option::deserialize")]
    pub recovery_hint: Option<models::RecoveryHint>,
}

impl DeltaFieldErrorBody {
    /// The 7-key per-delta envelope (always all keys present) the frontend auto-recovery consumes. Shared by every 422 delta error; `error` discriminates the cause.
    pub fn new(delta_ordinal: Option<i32>, delta_type: Option<String>, error: Error, field: Option<String>, reason: Option<String>, recoverable: bool, recovery_hint: Option<models::RecoveryHint>) -> DeltaFieldErrorBody {
        DeltaFieldErrorBody {
            delta_ordinal,
            delta_type,
            error,
            field,
            reason,
            recoverable,
            recovery_hint,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "malformed_delta_field")]
    MalformedDeltaField,
    #[serde(rename = "unknown_delta_type")]
    UnknownDeltaType,
    #[serde(rename = "delta_not_object")]
    DeltaNotObject,
    #[serde(rename = "delta_too_large")]
    DeltaTooLarge,
    #[serde(rename = "batch_too_large")]
    BatchTooLarge,
    #[serde(rename = "batch_count_exceeded")]
    BatchCountExceeded,
}

impl Default for Error {
    fn default() -> Error {
        Self::MalformedDeltaField
    }
}

