/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Edge : An edge connecting two nodes' ports.  Endpoints are given as `source_handle` / `target_handle`, each a port id. Unknown keys are ignored rather than rejected.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Edge {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "source_handle", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub source_handle: Option<Option<uuid::Uuid>>,
    #[serde(rename = "target_handle", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub target_handle: Option<Option<uuid::Uuid>>,
}

impl Edge {
    /// An edge connecting two nodes' ports.  Endpoints are given as `source_handle` / `target_handle`, each a port id. Unknown keys are ignored rather than rejected.
    pub fn new(id: uuid::Uuid) -> Edge {
        Edge {
            id,
            source_handle: None,
            target_handle: None,
        }
    }
}

