/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Finding : A single coherence finding over the graph that results from a delta batch. ``locator`` is the node / port / edge id (a string) the finding is about.  **``code`` is an OPEN set and is published as a plain string on purpose.** The codes are owned by the server and new ones are added additively as new coherence rules ship. Publishing the set as a closed enum made every generated client close it too — and a generated enum with no fallback arm fails to deserialize the WHOLE response the first time the server sends a code the client has not heard of. That turns every additive rule into a coordinated release, and turns a client that is merely out of date into one that cannot read a validate response at all.  So the contract is: **a consumer must tolerate codes it does not recognize** — render them, do not switch exhaustively on them. The known values are documented in the field description rather than enforced by the schema, because enforcing them here bought documentation at the cost of breaking clients.  ``severity`` stays closed: it is a two-valued verdict a consumer genuinely must branch on, and adding a third value WOULD be a breaking change that deserves a coordinated release.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Finding {
    /// Machine-readable finding code. Known values: `unsatisfied_input` (an input port with no incoming edge), `dangling_wire` (an edge whose endpoint does not exist), `type_mismatch` (a wired pair whose port types disagree). **This set is open and grows additively** — treat an unrecognized code as an opaque string and render it; do not fail on it.
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "locator")]
    pub locator: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "severity")]
    pub severity: Severity,
}

impl Finding {
    /// A single coherence finding over the graph that results from a delta batch. ``locator`` is the node / port / edge id (a string) the finding is about.  **``code`` is an OPEN set and is published as a plain string on purpose.** The codes are owned by the server and new ones are added additively as new coherence rules ship. Publishing the set as a closed enum made every generated client close it too — and a generated enum with no fallback arm fails to deserialize the WHOLE response the first time the server sends a code the client has not heard of. That turns every additive rule into a coordinated release, and turns a client that is merely out of date into one that cannot read a validate response at all.  So the contract is: **a consumer must tolerate codes it does not recognize** — render them, do not switch exhaustively on them. The known values are documented in the field description rather than enforced by the schema, because enforcing them here bought documentation at the cost of breaking clients.  ``severity`` stays closed: it is a two-valued verdict a consumer genuinely must branch on, and adding a third value WOULD be a breaking change that deserves a coordinated release.
    pub fn new(code: String, locator: String, message: String, severity: Severity) -> Finding {
        Finding {
            code,
            locator,
            message,
            severity,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Severity {
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "warning")]
    Warning,
}

impl Default for Severity {
    fn default() -> Severity {
        Self::Error
    }
}

