/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Finding : A single coherence finding over the graph that results from a delta batch. All three v1 ``code``s are ``error``-severity; ``severity`` keeps the ``warning`` arm in the contract for future advisory codes. ``locator`` is the node / port / edge id (a string) the finding is about.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Finding {
    #[serde(rename = "code")]
    pub code: Code,
    #[serde(rename = "locator")]
    pub locator: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "severity")]
    pub severity: Severity,
}

impl Finding {
    /// A single coherence finding over the graph that results from a delta batch. All three v1 ``code``s are ``error``-severity; ``severity`` keeps the ``warning`` arm in the contract for future advisory codes. ``locator`` is the node / port / edge id (a string) the finding is about.
    pub fn new(code: Code, locator: String, message: String, severity: Severity) -> Finding {
        Finding {
            code,
            locator,
            message,
            severity,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "unsatisfied_input")]
    UnsatisfiedInput,
    #[serde(rename = "dangling_wire")]
    DanglingWire,
    #[serde(rename = "type_mismatch")]
    TypeMismatch,
}

impl Default for Code {
    fn default() -> Code {
        Self::UnsatisfiedInput
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Severity {
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "warning")]
    Warning,
}

impl Default for Severity {
    fn default() -> Severity {
        Self::Error
    }
}

