/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FlattenBoundaryDelta : Flatten a boundary node: delete it and promote its children to its parent.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlattenBoundaryDelta {
    #[serde(rename = "node_id")]
    pub node_id: uuid::Uuid,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl FlattenBoundaryDelta {
    /// Flatten a boundary node: delete it and promote its children to its parent.
    pub fn new(node_id: uuid::Uuid, r#type: Type) -> FlattenBoundaryDelta {
        FlattenBoundaryDelta {
            node_id,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "flatten_boundary")]
    FlattenBoundary,
}

impl Default for Type {
    fn default() -> Type {
        Self::FlattenBoundary
    }
}

