/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GraphResponse {
    #[serde(rename = "branch")]
    pub branch: Box<models::BranchRef>,
    #[serde(rename = "edges")]
    pub edges: Vec<models::WireEdge>,
    #[serde(rename = "nodes")]
    pub nodes: Vec<models::WireNode>,
    #[serde(rename = "project_id")]
    pub project_id: uuid::Uuid,
    #[serde(rename = "version")]
    pub version: String,
}

impl GraphResponse {
    pub fn new(branch: models::BranchRef, edges: Vec<models::WireEdge>, nodes: Vec<models::WireNode>, project_id: uuid::Uuid, version: String) -> GraphResponse {
        GraphResponse {
            branch: Box::new(branch),
            edges,
            nodes,
            project_id,
            version,
        }
    }
}

