/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject3Detail {
    #[serde(rename = "code")]
    pub code: Code,
    #[serde(rename = "message")]
    pub message: String,
}

impl InlineObject3Detail {
    pub fn new(code: Code, message: String) -> InlineObject3Detail {
        InlineObject3Detail { code, message }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "invalid_name")]
    InvalidName,
    #[serde(rename = "unsupported_language")]
    UnsupportedLanguage,
    #[serde(rename = "unsupported_intent")]
    UnsupportedIntent,
}

impl Default for Code {
    fn default() -> Code {
        Self::InvalidName
    }
}
