/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject4DetailOneOf {
    #[serde(rename = "delta_ordinal", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub delta_ordinal: Option<Option<i32>>,
    #[serde(rename = "delta_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub delta_type: Option<Option<String>>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "field", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub field: Option<Option<String>>,
    #[serde(rename = "reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reason: Option<Option<String>>,
    #[serde(rename = "recoverable", skip_serializing_if = "Option::is_none")]
    pub recoverable: Option<bool>,
    #[serde(rename = "recovery_hint", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub recovery_hint: Option<Option<String>>,
}

impl InlineObject4DetailOneOf {
    pub fn new() -> InlineObject4DetailOneOf {
        InlineObject4DetailOneOf {
            delta_ordinal: None,
            delta_type: None,
            error: None,
            field: None,
            reason: None,
            recoverable: None,
            recovery_hint: None,
        }
    }
}

