/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MainBranchRef : The seeded main branch as returned by project-create.  Deliberately narrower than ``BranchMeta``: create returns only what the client can't mint locally and needs for its next call. Pinning the real shape (not ``BranchMeta``) keeps the generated SDK honest.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MainBranchRef {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "version")]
    pub version: i32,
}

impl MainBranchRef {
    /// The seeded main branch as returned by project-create.  Deliberately narrower than ``BranchMeta``: create returns only what the client can't mint locally and needs for its next call. Pinning the real shape (not ``BranchMeta``) keeps the generated SDK honest.
    pub fn new(id: uuid::Uuid, version: i32) -> MainBranchRef {
        MainBranchRef {
            id,
            version,
        }
    }
}

