/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Node : A behavior or boundary node.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Node {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<models::NodeData>>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "parent_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<Option<uuid::Uuid>>,
}

impl Node {
    /// A behavior or boundary node.
    pub fn new(id: uuid::Uuid, kind: Kind) -> Node {
        Node {
            data: None,
            id,
            kind,
            parent_id: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "behavior")]
    Behavior,
    #[serde(rename = "boundary")]
    Boundary,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Behavior
    }
}

