/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NodeData : A node's data payload; its shape varies by kind and whether the node is external.  On update, key-presence semantics apply: a field present with a null value is set to null, while an omitted field is left unchanged. All fields are optional at the type level — cross-field rules (e.g. behavior nodes reject `user_kind`; external nodes require `external_kind`) are enforced server-side, so a partial update is not blocked by \"missing required field\" errors that don't apply to it.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeData {
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<Vec<models::Port>>,
    #[serde(rename = "constraints", skip_serializing_if = "Option::is_none")]
    pub constraints: Option<Vec<String>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "documentation_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub documentation_url: Option<Option<String>>,
    #[serde(rename = "external_kind", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub external_kind: Option<Option<String>>,
    #[serde(rename = "inputs", skip_serializing_if = "Option::is_none")]
    pub inputs: Option<Vec<models::Port>>,
    #[serde(rename = "isTestNode", skip_serializing_if = "Option::is_none")]
    pub is_test_node: Option<bool>,
    #[serde(rename = "is_external", skip_serializing_if = "Option::is_none")]
    pub is_external: Option<bool>,
    #[serde(rename = "kind", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub kind: Option<Option<Kind>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "outputs", skip_serializing_if = "Option::is_none")]
    pub outputs: Option<Vec<models::Port>>,
    #[serde(rename = "parent_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "path_prefix", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub path_prefix: Option<Option<String>>,
    #[serde(rename = "protocol", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<Option<String>>,
    #[serde(rename = "source_decisions", skip_serializing_if = "Option::is_none")]
    pub source_decisions: Option<Vec<uuid::Uuid>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "user_kind", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_kind: Option<Option<String>>,
    #[serde(rename = "verifications", skip_serializing_if = "Option::is_none")]
    pub verifications: Option<Vec<models::Verification>>,
}

impl NodeData {
    /// A node's data payload; its shape varies by kind and whether the node is external.  On update, key-presence semantics apply: a field present with a null value is set to null, while an omitted field is left unchanged. All fields are optional at the type level — cross-field rules (e.g. behavior nodes reject `user_kind`; external nodes require `external_kind`) are enforced server-side, so a partial update is not blocked by \"missing required field\" errors that don't apply to it.
    pub fn new() -> NodeData {
        NodeData {
            config: None,
            constraints: None,
            description: None,
            documentation_url: None,
            external_kind: None,
            inputs: None,
            is_test_node: None,
            is_external: None,
            kind: None,
            name: None,
            outputs: None,
            parent_id: None,
            path_prefix: None,
            protocol: None,
            source_decisions: None,
            status: None,
            user_kind: None,
            verifications: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "behavior")]
    Behavior,
    #[serde(rename = "boundary")]
    Boundary,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Behavior
    }
}

