/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NotFoundBody : Returned when a delta targets a node that doesn't exist (404). `node_id` identifies the missing target.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotFoundBody {
    #[serde(rename = "error")]
    pub error: Error,
    #[serde(rename = "node_id")]
    pub node_id: String,
    #[serde(rename = "reason")]
    pub reason: String,
}

impl NotFoundBody {
    /// Returned when a delta targets a node that doesn't exist (404). `node_id` identifies the missing target.
    pub fn new(error: Error, node_id: String, reason: String) -> NotFoundBody {
        NotFoundBody {
            error,
            node_id,
            reason,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "not_found")]
    NotFound,
}

impl Default for Error {
    fn default() -> Error {
        Self::NotFound
    }
}

