/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Port : An input, output, or config port on a node.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Port {
    #[serde(rename = "contract_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contract_name: Option<Option<String>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "external", skip_serializing_if = "Option::is_none")]
    pub external: Option<bool>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl Port {
    /// An input, output, or config port on a node.
    pub fn new(id: uuid::Uuid) -> Port {
        Port {
            contract_name: None,
            description: None,
            external: None,
            id,
            name: None,
            r#type: None,
        }
    }
}

