/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectOut {
    #[serde(rename = "archived")]
    pub archived: bool,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "h2o_schema_version")]
    pub h2o_schema_version: i32,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "intent", deserialize_with = "Option::deserialize")]
    pub intent: Option<String>,
    #[serde(rename = "language", deserialize_with = "Option::deserialize")]
    pub language: Option<String>,
    #[serde(rename = "last_opened_at", deserialize_with = "Option::deserialize")]
    pub last_opened_at: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl ProjectOut {
    pub fn new(archived: bool, created_at: String, h2o_schema_version: i32, id: uuid::Uuid, intent: Option<String>, language: Option<String>, last_opened_at: Option<String>, name: String, updated_at: String) -> ProjectOut {
        ProjectOut {
            archived,
            created_at,
            h2o_schema_version,
            id,
            intent,
            language,
            last_opened_at,
            name,
            updated_at,
        }
    }
}

