/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectPatchResponse : Rename/archive returns the project alone.  No ``main_branch``, unlike create: the branch is not affected by either edit, and echoing it would imply otherwise.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectPatchResponse {
    #[serde(rename = "project")]
    pub project: Box<models::ProjectOut>,
    #[serde(rename = "version")]
    pub version: String,
}

impl ProjectPatchResponse {
    /// Rename/archive returns the project alone.  No ``main_branch``, unlike create: the branch is not affected by either edit, and echoing it would imply otherwise.
    pub fn new(project: models::ProjectOut, version: String) -> ProjectPatchResponse {
        ProjectPatchResponse {
            project: Box::new(project),
            version,
        }
    }
}

