/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectCreateResponse {
    #[serde(rename = "main_branch")]
    pub main_branch: Box<models::MainBranchRef>,
    #[serde(rename = "project")]
    pub project: Box<models::ProjectOut>,
    #[serde(rename = "version")]
    pub version: String,
}

impl ProjectCreateResponse {
    pub fn new(
        main_branch: models::MainBranchRef,
        project: models::ProjectOut,
        version: String,
    ) -> ProjectCreateResponse {
        ProjectCreateResponse {
            main_branch: Box::new(main_branch),
            project: Box::new(project),
            version,
        }
    }
}
