/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecoveryHint : The finite set of recovery hints a client may receive in `ApiError.recovery_hint`:      - \"regenerate_uuid\" — mint a new UUID at `field` and retry     - \"drop_field\"      — delete `field` and retry     - null              — not auto-recoverable; user intervention needed  A closed set, so integrations can switch over the value; a new hint is added here deliberately, giving clients a chance to handle it.
/// The finite set of recovery hints a client may receive in `ApiError.recovery_hint`:      - \"regenerate_uuid\" — mint a new UUID at `field` and retry     - \"drop_field\"      — delete `field` and retry     - null              — not auto-recoverable; user intervention needed  A closed set, so integrations can switch over the value; a new hint is added here deliberately, giving clients a chance to handle it.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RecoveryHint {
    #[serde(rename = "regenerate_uuid")]
    RegenerateUuid,
    #[serde(rename = "drop_field")]
    DropField,

}

impl std::fmt::Display for RecoveryHint {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RegenerateUuid => write!(f, "regenerate_uuid"),
            Self::DropField => write!(f, "drop_field"),
        }
    }
}

impl Default for RecoveryHint {
    fn default() -> RecoveryHint {
        Self::RegenerateUuid
    }
}

