/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReparentNodeDelta : Move a node to a new parent (or to top-level).  `parent_id` must be present on the wire (use null for top-level); an absent key is rejected, so a client bug surfaces as a clean parse error rather than an ambiguous no-op.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReparentNodeDelta {
    #[serde(rename = "node_id")]
    pub node_id: uuid::Uuid,
    #[serde(rename = "parent_id", deserialize_with = "Option::deserialize")]
    pub parent_id: Option<uuid::Uuid>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ReparentNodeDelta {
    /// Move a node to a new parent (or to top-level).  `parent_id` must be present on the wire (use null for top-level); an absent key is rejected, so a client bug surfaces as a clean parse error rather than an ambiguous no-op.
    pub fn new(node_id: uuid::Uuid, parent_id: Option<uuid::Uuid>, r#type: Type) -> ReparentNodeDelta {
        ReparentNodeDelta {
            node_id,
            parent_id,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "reparent_node")]
    ReparentNode,
}

impl Default for Type {
    fn default() -> Type {
        Self::ReparentNode
    }
}

