/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubtreeResponse : A node plus its descendants to a bounded depth.  ``nodes`` EXCLUDES ``root``. ``truncated`` is true when the walk stopped with descendants still below it — a caller that cannot distinguish a complete cell from a slice will treat a slice as complete, so the signal is explicit rather than inferred from ``depth``.  ``cross_boundary_edges`` carries edges with exactly one endpoint inside the returned set: real dependencies of this slice, which a scoped read would otherwise hide.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubtreeResponse {
    #[serde(rename = "branch")]
    pub branch: Box<models::BranchRef>,
    #[serde(rename = "cross_boundary_edges")]
    pub cross_boundary_edges: Vec<models::WireEdge>,
    #[serde(rename = "depth")]
    pub depth: i32,
    #[serde(rename = "edges")]
    pub edges: Vec<models::WireEdge>,
    #[serde(rename = "nodes")]
    pub nodes: Vec<models::WireNode>,
    /// Dotted path for every node returned that has one, keyed by node id. Server-rendered because a scoped read returns a SLICE: the ancestors a path is built from are not in the payload, so a client cannot derive it. Every returned node appears in exactly one of `paths` or `unaddressable` — index this map for anything not listed there.
    #[serde(rename = "paths")]
    pub paths: std::collections::HashMap<String, String>,
    #[serde(rename = "project_id")]
    pub project_id: uuid::Uuid,
    #[serde(rename = "root")]
    pub root: Box<models::WireNode>,
    #[serde(rename = "truncated")]
    pub truncated: bool,
    /// Nodes that could not be given a dotted path, keyed by node id, with the reason: `empty_name` (the node, or an ancestor, has no name — legal while designing), `reserved_separator` (a name contains `.`), or `ambiguous` (two returned nodes would render the same path, so neither is safe to act on). These are data conditions a user fixes by renaming, not errors.
    #[serde(rename = "unaddressable")]
    pub unaddressable: std::collections::HashMap<String, String>,
    #[serde(rename = "version")]
    pub version: String,
}

impl SubtreeResponse {
    /// A node plus its descendants to a bounded depth.  ``nodes`` EXCLUDES ``root``. ``truncated`` is true when the walk stopped with descendants still below it — a caller that cannot distinguish a complete cell from a slice will treat a slice as complete, so the signal is explicit rather than inferred from ``depth``.  ``cross_boundary_edges`` carries edges with exactly one endpoint inside the returned set: real dependencies of this slice, which a scoped read would otherwise hide.
    pub fn new(branch: models::BranchRef, cross_boundary_edges: Vec<models::WireEdge>, depth: i32, edges: Vec<models::WireEdge>, nodes: Vec<models::WireNode>, paths: std::collections::HashMap<String, String>, project_id: uuid::Uuid, root: models::WireNode, truncated: bool, unaddressable: std::collections::HashMap<String, String>, version: String) -> SubtreeResponse {
        SubtreeResponse {
            branch: Box::new(branch),
            cross_boundary_edges,
            depth,
            edges,
            nodes,
            paths,
            project_id,
            root: Box::new(root),
            truncated,
            unaddressable,
            version,
        }
    }
}

