/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateNodeDataDelta : Update a node's data, with key-presence partial semantics.  `after` may be empty; whether a field is present in `after` distinguishes \"set this field\" from \"leave it unchanged\".
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateNodeDataDelta {
    #[serde(rename = "after")]
    pub after: Box<models::NodeData>,
    #[serde(rename = "node_id")]
    pub node_id: uuid::Uuid,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl UpdateNodeDataDelta {
    /// Update a node's data, with key-presence partial semantics.  `after` may be empty; whether a field is present in `after` distinguishes \"set this field\" from \"leave it unchanged\".
    pub fn new(after: models::NodeData, node_id: uuid::Uuid, r#type: Type) -> UpdateNodeDataDelta {
        UpdateNodeDataDelta {
            after: Box::new(after),
            node_id,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "update_node_data")]
    UpdateNodeData,
}

impl Default for Type {
    fn default() -> Type {
        Self::UpdateNodeData
    }
}

