/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1CreateProjectBody : Body for ``POST /v1/projects``. Only ``name`` is required; ``language`` and ``intent`` default server-side to ``python``/``cli`` (mirrored by the CLI ``hydrate new`` defaults).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1CreateProjectBody {
    #[serde(rename = "intent", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub intent: Option<Option<String>>,
    #[serde(rename = "language", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub language: Option<Option<String>>,
    /// Project name. Unique per-user, case-insensitive.
    #[serde(rename = "name")]
    pub name: String,
}

impl V1CreateProjectBody {
    /// Body for ``POST /v1/projects``. Only ``name`` is required; ``language`` and ``intent`` default server-side to ``python``/``cli`` (mirrored by the CLI ``hydrate new`` defaults).
    pub fn new(name: String) -> V1CreateProjectBody {
        V1CreateProjectBody {
            intent: None,
            language: None,
            name,
        }
    }
}

