/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1CreateBranchBody : Body for ``POST /v1/projects/{pid}/branches``. ``name`` defaults to the next ``main-work[-N]`` for the caller, so a bodyless POST works.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1CreateBranchBody {
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
}

impl V1CreateBranchBody {
    /// Body for ``POST /v1/projects/{pid}/branches``. ``name`` defaults to the next ``main-work[-N]`` for the caller, so a bodyless POST works.
    pub fn new() -> V1CreateBranchBody {
        V1CreateBranchBody {
            name: None,
        }
    }
}

