/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum V1DeltasBodyDeltasInner {
    #[serde(rename="add_node")]
    AddNode(Box<models::AddNodeDelta>),
    #[serde(rename="delete_node")]
    DeleteNode(Box<models::DeleteNodeDelta>),
    #[serde(rename="update_node_data")]
    UpdateNodeData(Box<models::UpdateNodeDataDelta>),
    #[serde(rename="reparent_node")]
    ReparentNode(Box<models::ReparentNodeDelta>),
    #[serde(rename="add_edge")]
    AddEdge(Box<models::AddEdgeDelta>),
    #[serde(rename="delete_edge")]
    DeleteEdge(Box<models::DeleteEdgeDelta>),
    #[serde(rename="flatten_boundary")]
    FlattenBoundary(Box<models::FlattenBoundaryDelta>),
}

impl Default for V1DeltasBodyDeltasInner {
    fn default() -> Self {
        Self::AddNode(Default::default())
    }
}


