/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1DeltasBody : Request body for ``POST /v1/branches/{bid}/deltas``.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1DeltasBody {
    /// Ordered list of delta operations to apply. Each must carry a `type` field in the closed write-surface vocabulary (add_node / delete_node / update_node_data / reparent_node / add_edge / delete_edge / flatten_boundary). Empty list returns 200 with `applied: false` and no version bump.
    #[serde(rename = "deltas", skip_serializing_if = "Option::is_none")]
    pub deltas: Option<Vec<models::V1DeltasBodyDeltasInner>>,
    /// The branch.version the client believes is current. If it doesn't match the server's view at commit time, the route 409s with the actual current_version in the detail.
    #[serde(rename = "expected_version")]
    pub expected_version: u32,
    #[serde(rename = "positions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub positions: Option<Option<std::collections::HashMap<String, models::V1NodePosition>>>,
}

impl V1DeltasBody {
    /// Request body for ``POST /v1/branches/{bid}/deltas``.
    pub fn new(expected_version: u32) -> V1DeltasBody {
        V1DeltasBody {
            deltas: None,
            expected_version,
            positions: None,
        }
    }
}

