/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1NodePosition : A single explicit pin coordinate on the `/v1/` write surface.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1NodePosition {
    #[serde(rename = "x")]
    pub x: f64,
    #[serde(rename = "y")]
    pub y: f64,
}

impl V1NodePosition {
    /// A single explicit pin coordinate on the `/v1/` write surface.
    pub fn new(x: f64, y: f64) -> V1NodePosition {
        V1NodePosition {
            x,
            y,
        }
    }
}

