/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1PatchProjectBody : Body for ``PATCH /v1/projects/{project_id}``.  Deliberately narrower than the legacy session router's patch body, which also carries ``language``, ``intent`` and ``layout_mode``. Those are creation-time metadata on the agent surface; widening this later is additive, whereas shipping fields the CLI has no verb for is not.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PatchProjectBody {
    #[serde(rename = "archived", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub archived: Option<Option<bool>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
}

impl V1PatchProjectBody {
    /// Body for ``PATCH /v1/projects/{project_id}``.  Deliberately narrower than the legacy session router's patch body, which also carries ``language``, ``intent`` and ``layout_mode``. Those are creation-time metadata on the agent surface; widening this later is additive, whereas shipping fields the CLI has no verb for is not.
    pub fn new() -> V1PatchProjectBody {
        V1PatchProjectBody {
            archived: None,
            name: None,
        }
    }
}

