/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1PatchBranchBody : Body for ``PATCH /v1/branches/{branch_id}``. Rename only — a branch has no archive state the way a project does; discard (the DELETE route beside this one) is already the non-listed-but-recoverable-by-id shape a project gets from archiving. ``name`` is required (not optional-with-a- no-fields-guard, unlike the project patch body): there is only one field, so an absent body is already a 422 from Pydantic without extra code.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PatchBranchBody {
    /// New name for the branch.
    #[serde(rename = "name")]
    pub name: String,
}

impl V1PatchBranchBody {
    /// Body for ``PATCH /v1/branches/{branch_id}``. Rename only — a branch has no archive state the way a project does; discard (the DELETE route beside this one) is already the non-listed-but-recoverable-by-id shape a project gets from archiving. ``name`` is required (not optional-with-a- no-fields-guard, unlike the project patch body): there is only one field, so an absent body is already a 422 from Pydantic without extra code.
    pub fn new(name: String) -> V1PatchBranchBody {
        V1PatchBranchBody {
            name,
        }
    }
}

