/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V1ValidateBody : Request body for ``POST /v1/branches/{bid}/validate``.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ValidateBody {
    #[serde(rename = "deltas", skip_serializing_if = "Option::is_none")]
    pub deltas: Option<Vec<models::V1DeltasBodyDeltasInner>>,
}

impl V1ValidateBody {
    /// Request body for ``POST /v1/branches/{bid}/validate``.
    pub fn new() -> V1ValidateBody {
        V1ValidateBody {
            deltas: None,
        }
    }
}

