/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidateResponse {
    #[serde(rename = "branch")]
    pub branch: Box<models::BranchRef>,
    #[serde(rename = "delta_count")]
    pub delta_count: i32,
    #[serde(rename = "project_id")]
    pub project_id: uuid::Uuid,
    #[serde(rename = "valid")]
    pub valid: bool,
    #[serde(rename = "version")]
    pub version: String,
}

impl ValidateResponse {
    pub fn new(branch: models::BranchRef, delta_count: i32, project_id: uuid::Uuid, valid: bool, version: String) -> ValidateResponse {
        ValidateResponse {
            branch: Box::new(branch),
            delta_count,
            project_id,
            valid,
            version,
        }
    }
}

