/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionConflictBody {
    #[serde(rename = "current_version")]
    pub current_version: i32,
    #[serde(rename = "error")]
    pub error: Error,
}

impl VersionConflictBody {
    pub fn new(current_version: i32, error: Error) -> VersionConflictBody {
        VersionConflictBody {
            current_version,
            error,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "version_conflict")]
    VersionConflict,
}

impl Default for Error {
    fn default() -> Error {
        Self::VersionConflict
    }
}

