/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WireEdge : Read-path edge: `source`/`target` are server-derived NODE ids (absent from the client-authored `h2o.types.Edge`); `*_handle` are the PORT ids.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WireEdge {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "source")]
    pub source: uuid::Uuid,
    #[serde(rename = "source_handle", deserialize_with = "Option::deserialize")]
    pub source_handle: Option<uuid::Uuid>,
    #[serde(rename = "target")]
    pub target: uuid::Uuid,
    #[serde(rename = "target_handle", deserialize_with = "Option::deserialize")]
    pub target_handle: Option<uuid::Uuid>,
}

impl WireEdge {
    /// Read-path edge: `source`/`target` are server-derived NODE ids (absent from the client-authored `h2o.types.Edge`); `*_handle` are the PORT ids.
    pub fn new(id: uuid::Uuid, source: uuid::Uuid, source_handle: Option<uuid::Uuid>, target: uuid::Uuid, target_handle: Option<uuid::Uuid>) -> WireEdge {
        WireEdge {
            id,
            source,
            source_handle,
            target,
            target_handle,
        }
    }
}

