/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WireNode {
    #[serde(rename = "data")]
    pub data: Box<models::WireNodeData>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "parent_id", deserialize_with = "Option::deserialize")]
    pub parent_id: Option<uuid::Uuid>,
    #[serde(rename = "position")]
    pub position: Box<models::Position>,
}

impl WireNode {
    pub fn new(data: models::WireNodeData, id: uuid::Uuid, kind: Kind, parent_id: Option<uuid::Uuid>, position: models::Position) -> WireNode {
        WireNode {
            data: Box::new(data),
            id,
            kind,
            parent_id,
            position: Box::new(position),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "behavior")]
    Behavior,
    #[serde(rename = "boundary")]
    Boundary,
    #[serde(rename = "state")]
    State,
    #[serde(rename = "io")]
    Io,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Behavior
    }
}

