/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WireVerification {
    #[serde(rename = "author")]
    pub author: Author,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
}

impl WireVerification {
    pub fn new(author: Author, id: uuid::Uuid, text: String) -> WireVerification {
        WireVerification {
            author,
            id,
            text,
            r#type: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Author {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "agent")]
    Agent,
}

impl Default for Author {
    fn default() -> Author {
        Self::User
    }
}

