/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WireNodeData : Read-path node `data`. NOT `h2o.NodeData`: the response omits `kind`/`parent_id` (those live on the wrapper) and emits the boundary/ external scalars matrix-conditionally — so the matrix fields are optional (absent = not-applicable-to-kind).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WireNodeData {
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<Vec<models::WirePort>>,
    #[serde(rename = "constraints", skip_serializing_if = "Option::is_none")]
    pub constraints: Option<Vec<String>>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "documentation_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub documentation_url: Option<Option<String>>,
    #[serde(rename = "external_kind", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub external_kind: Option<Option<String>>,
    #[serde(rename = "inputs", skip_serializing_if = "Option::is_none")]
    pub inputs: Option<Vec<models::WirePort>>,
    #[serde(rename = "is_external")]
    pub is_external: bool,
    #[serde(rename = "is_test_node")]
    pub is_test_node: bool,
    #[serde(rename = "language", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub language: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "outputs", skip_serializing_if = "Option::is_none")]
    pub outputs: Option<Vec<models::WirePort>>,
    #[serde(rename = "path_prefix", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub path_prefix: Option<Option<String>>,
    #[serde(rename = "protocol", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<Option<String>>,
    #[serde(rename = "source_decisions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub source_decisions: Option<Option<Vec<String>>>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "user_kind", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_kind: Option<Option<String>>,
    #[serde(rename = "verifications", skip_serializing_if = "Option::is_none")]
    pub verifications: Option<Vec<models::WireVerification>>,
}

impl WireNodeData {
    /// Read-path node `data`. NOT `h2o.NodeData`: the response omits `kind`/`parent_id` (those live on the wrapper) and emits the boundary/ external scalars matrix-conditionally — so the matrix fields are optional (absent = not-applicable-to-kind).
    pub fn new(description: String, is_external: bool, is_test_node: bool, name: String, status: String) -> WireNodeData {
        WireNodeData {
            config: None,
            constraints: None,
            description,
            documentation_url: None,
            external_kind: None,
            inputs: None,
            is_external,
            is_test_node,
            language: None,
            name,
            outputs: None,
            path_prefix: None,
            protocol: None,
            source_decisions: None,
            status,
            user_kind: None,
            verifications: None,
        }
    }
}

