/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`apply_branch_deltas_v1_branches_branch_id_deltas_post`]
#[derive(Clone, Debug)]
pub struct ApplyBranchDeltasV1BranchesBranchIdDeltasPostParams {
    /// The branch to apply to.
    pub branch_id: String,
    pub v1_deltas_body: models::V1DeltasBody
}

/// struct for passing parameters to the method [`create_branch_v1_projects_project_id_branches_post`]
#[derive(Clone, Debug)]
pub struct CreateBranchV1ProjectsProjectIdBranchesPostParams {
    /// The project to fork a branch in.
    pub project_id: String,
    pub v1_create_branch_body: models::V1CreateBranchBody
}

/// struct for passing parameters to the method [`fetch_branch_boundary_v1_branches_branch_id_boundary_node_id_get`]
#[derive(Clone, Debug)]
pub struct FetchBranchBoundaryV1BranchesBranchIdBoundaryNodeIdGetParams {
    /// The branch to read.
    pub branch_id: String,
    /// The boundary node to inspect.
    pub node_id: String
}

/// struct for passing parameters to the method [`fetch_branch_graph_v1_branches_branch_id_graph_get`]
#[derive(Clone, Debug)]
pub struct FetchBranchGraphV1BranchesBranchIdGraphGetParams {
    /// The branch to read.
    pub branch_id: String
}

/// struct for passing parameters to the method [`fetch_branch_node_v1_branches_branch_id_node_node_id_get`]
#[derive(Clone, Debug)]
pub struct FetchBranchNodeV1BranchesBranchIdNodeNodeIdGetParams {
    /// The branch to read.
    pub branch_id: String,
    /// The node to read.
    pub node_id: String
}

/// struct for passing parameters to the method [`fetch_branch_subtree_v1_branches_branch_id_subtree_node_id_get`]
#[derive(Clone, Debug)]
pub struct FetchBranchSubtreeV1BranchesBranchIdSubtreeNodeIdGetParams {
    /// The branch to read.
    pub branch_id: String,
    /// The node to root the subtree at.
    pub node_id: String,
    /// How many levels of descendants to include. 1 = direct children only.
    pub depth: Option<u32>
}

/// struct for passing parameters to the method [`list_branches_v1_projects_project_id_branches_get`]
#[derive(Clone, Debug)]
pub struct ListBranchesV1ProjectsProjectIdBranchesGetParams {
    /// The project to list branches for.
    pub project_id: String
}

/// struct for passing parameters to the method [`validate_branch_deltas_v1_branches_branch_id_validate_post`]
#[derive(Clone, Debug)]
pub struct ValidateBranchDeltasV1BranchesBranchIdValidatePostParams {
    /// The branch to validate against.
    pub branch_id: String,
    pub v1_validate_body: models::V1ValidateBody
}


/// struct for typed errors of method [`apply_branch_deltas_v1_branches_branch_id_deltas_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApplyBranchDeltasV1BranchesBranchIdDeltasPostError {
    Status401(models::InlineObject7),
    Status403(models::InlineObject),
    Status404(models::ApplyBranchDeltasV1BranchesBranchIdDeltasPost404Response),
    Status409(models::ApplyBranchDeltasV1BranchesBranchIdDeltasPost409Response),
    Status422(models::ApplyBranchDeltasV1BranchesBranchIdDeltasPost422Response),
    Status429(models::InlineObject6),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_branch_v1_projects_project_id_branches_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateBranchV1ProjectsProjectIdBranchesPostError {
    Status401(models::InlineObject7),
    Status403(models::InlineObject),
    Status404(models::InlineObject1),
    Status422(models::HttpValidationError),
    Status429(models::InlineObject6),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_branch_boundary_v1_branches_branch_id_boundary_node_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchBranchBoundaryV1BranchesBranchIdBoundaryNodeIdGetError {
    Status401(models::InlineObject7),
    Status403(models::InlineObject),
    Status404(models::InlineObject1),
    Status422(models::HttpValidationError),
    Status429(models::InlineObject6),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_branch_graph_v1_branches_branch_id_graph_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchBranchGraphV1BranchesBranchIdGraphGetError {
    Status401(models::InlineObject7),
    Status403(models::InlineObject),
    Status404(models::InlineObject1),
    Status422(models::HttpValidationError),
    Status429(models::InlineObject6),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_branch_node_v1_branches_branch_id_node_node_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchBranchNodeV1BranchesBranchIdNodeNodeIdGetError {
    Status401(models::InlineObject7),
    Status403(models::InlineObject),
    Status404(models::InlineObject1),
    Status422(models::HttpValidationError),
    Status429(models::InlineObject6),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_branch_subtree_v1_branches_branch_id_subtree_node_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchBranchSubtreeV1BranchesBranchIdSubtreeNodeIdGetError {
    Status401(models::InlineObject7),
    Status403(models::InlineObject),
    Status404(models::InlineObject1),
    Status422(models::HttpValidationError),
    Status429(models::InlineObject6),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_branches_v1_projects_project_id_branches_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListBranchesV1ProjectsProjectIdBranchesGetError {
    Status401(models::InlineObject7),
    Status403(models::InlineObject),
    Status404(models::InlineObject1),
    Status422(models::HttpValidationError),
    Status429(models::InlineObject6),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`validate_branch_deltas_v1_branches_branch_id_validate_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ValidateBranchDeltasV1BranchesBranchIdValidatePostError {
    Status401(models::InlineObject7),
    Status403(models::InlineObject),
    Status404(models::ApplyBranchDeltasV1BranchesBranchIdDeltasPost404Response),
    Status422(models::ApplyBranchDeltasV1BranchesBranchIdDeltasPost422Response),
    Status429(models::InlineObject6),
    UnknownValue(serde_json::Value),
}


/// Apply an ordered batch of structural changes to a branch under optimistic concurrency. Pass the `version` from the branch read as `expected_version`; a 409 with `current_version` is returned if the branch moved underneath you. Pair with the `Idempotency-Key` header for at-most-once apply across retries.
pub async fn apply_branch_deltas_v1_branches_branch_id_deltas_post(configuration: &configuration::Configuration, params: ApplyBranchDeltasV1BranchesBranchIdDeltasPostParams) -> Result<models::DeltaApplyResponse, Error<ApplyBranchDeltasV1BranchesBranchIdDeltasPostError>> {

    let uri_str = format!("{}/v1/branches/{branch_id}/deltas", configuration.base_path, branch_id=crate::apis::urlencode(params.branch_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.v1_deltas_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeltaApplyResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeltaApplyResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApplyBranchDeltasV1BranchesBranchIdDeltasPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Fork a new working branch from the project's main branch. The branch is copied from main's current state and owned by you; your changes stay isolated on it until merged. Requires an editor role, and there is a per-project limit on how many active branches you can hold at once.
pub async fn create_branch_v1_projects_project_id_branches_post(configuration: &configuration::Configuration, params: CreateBranchV1ProjectsProjectIdBranchesPostParams) -> Result<models::BranchCreateResponse, Error<CreateBranchV1ProjectsProjectIdBranchesPostError>> {

    let uri_str = format!("{}/v1/projects/{project_id}/branches", configuration.base_path, project_id=crate::apis::urlencode(params.project_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.v1_create_branch_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BranchCreateResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BranchCreateResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateBranchV1ProjectsProjectIdBranchesPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a boundary node, its direct children, and the edges between those children — on this branch. Edges that cross the boundary belong to the parent cell's inspection and are not returned.
pub async fn fetch_branch_boundary_v1_branches_branch_id_boundary_node_id_get(configuration: &configuration::Configuration, params: FetchBranchBoundaryV1BranchesBranchIdBoundaryNodeIdGetParams) -> Result<models::BoundaryResponse, Error<FetchBranchBoundaryV1BranchesBranchIdBoundaryNodeIdGetError>> {

    let uri_str = format!("{}/v1/branches/{branch_id}/boundary/{node_id}", configuration.base_path, branch_id=crate::apis::urlencode(params.branch_id), node_id=crate::apis::urlencode(params.node_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BoundaryResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BoundaryResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchBranchBoundaryV1BranchesBranchIdBoundaryNodeIdGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Read the full graph (nodes, ports, edges, version) of a specific branch. Use the returned `version` as `expected_version` on a subsequent apply to that branch.
pub async fn fetch_branch_graph_v1_branches_branch_id_graph_get(configuration: &configuration::Configuration, params: FetchBranchGraphV1BranchesBranchIdGraphGetParams) -> Result<models::GraphResponse, Error<FetchBranchGraphV1BranchesBranchIdGraphGetError>> {

    let uri_str = format!("{}/v1/branches/{branch_id}/graph", configuration.base_path, branch_id=crate::apis::urlencode(params.branch_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GraphResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GraphResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchBranchGraphV1BranchesBranchIdGraphGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a node, every node one edge away from it, and those edges — on this branch. The scoped read an agent uses to load just the context around what it is about to change.
pub async fn fetch_branch_node_v1_branches_branch_id_node_node_id_get(configuration: &configuration::Configuration, params: FetchBranchNodeV1BranchesBranchIdNodeNodeIdGetParams) -> Result<models::NodeNeighborhoodResponse, Error<FetchBranchNodeV1BranchesBranchIdNodeNodeIdGetError>> {

    let uri_str = format!("{}/v1/branches/{branch_id}/node/{node_id}", configuration.base_path, branch_id=crate::apis::urlencode(params.branch_id), node_id=crate::apis::urlencode(params.node_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NodeNeighborhoodResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NodeNeighborhoodResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchBranchNodeV1BranchesBranchIdNodeNodeIdGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a node and its descendants down to `depth` levels on this branch, with the edges among them. The scoped counterpart to `GET /v1/branches/{branch_id}/graph`: bounded by `depth` rather than by the size of the branch, so reading a slice of a large project never puts the whole graph on the wire.
pub async fn fetch_branch_subtree_v1_branches_branch_id_subtree_node_id_get(configuration: &configuration::Configuration, params: FetchBranchSubtreeV1BranchesBranchIdSubtreeNodeIdGetParams) -> Result<models::SubtreeResponse, Error<FetchBranchSubtreeV1BranchesBranchIdSubtreeNodeIdGetError>> {

    let uri_str = format!("{}/v1/branches/{branch_id}/subtree/{node_id}", configuration.base_path, branch_id=crate::apis::urlencode(params.branch_id), node_id=crate::apis::urlencode(params.node_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.depth {
        req_builder = req_builder.query(&[("depth", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SubtreeResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SubtreeResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchBranchSubtreeV1BranchesBranchIdSubtreeNodeIdGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// List your active working branches on this project. The protected main branch is not included. Each branch is a unit of work you can read and apply changes to before merging into main.
pub async fn list_branches_v1_projects_project_id_branches_get(configuration: &configuration::Configuration, params: ListBranchesV1ProjectsProjectIdBranchesGetParams) -> Result<models::BranchListResponse, Error<ListBranchesV1ProjectsProjectIdBranchesGetError>> {

    let uri_str = format!("{}/v1/projects/{project_id}/branches", configuration.base_path, project_id=crate::apis::urlencode(params.project_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BranchListResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BranchListResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListBranchesV1ProjectsProjectIdBranchesGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Dry-run a delta batch and get back the full coherence report over the graph that would result — never mutating the branch. Returns 200 with `{valid, findings}`: `findings` is the complete list of coherence problems (an input port with no incoming edge, a wire pinned to a missing port, or an edge whose endpoint types differ), and `valid` is true only when there are no error-severity findings. The verdict is in the body, so an incoherent graph is still a 200. A 4xx is returned only for a request that can't be processed at all (a malformed body or an unknown delta type). An empty delta list reports the branch's current coherence.
pub async fn validate_branch_deltas_v1_branches_branch_id_validate_post(configuration: &configuration::Configuration, params: ValidateBranchDeltasV1BranchesBranchIdValidatePostParams) -> Result<models::ValidateResponse, Error<ValidateBranchDeltasV1BranchesBranchIdValidatePostError>> {

    let uri_str = format!("{}/v1/branches/{branch_id}/validate", configuration.base_path, branch_id=crate::apis::urlencode(params.branch_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.v1_validate_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ValidateResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ValidateResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ValidateBranchDeltasV1BranchesBranchIdValidatePostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

