/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`get_decision_v1_decisions_decision_id_get`]
#[derive(Clone, Debug)]
pub struct GetDecisionV1DecisionsDecisionIdGetParams {
    pub decision_id: String,
}

/// struct for passing parameters to the method [`list_decisions_v1_decisions_get`]
#[derive(Clone, Debug)]
pub struct ListDecisionsV1DecisionsGetParams {
    /// Required. Decisions are project-scoped and the read is authorized per project.
    pub project_id: String,
    /// Narrow to these states. Only settled outcomes are served; anything else is refused with 422 state_not_readable.
    pub state: Option<Vec<String>>,
    /// Narrow to these altitudes. Must be a subset of the calling principal's altitude membership; otherwise 422 owner_layer_not_permitted.
    pub owner_layer: Option<Vec<String>>,
    pub limit: Option<u32>,
    pub offset: Option<u32>,
}

/// struct for typed errors of method [`get_decision_v1_decisions_decision_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetDecisionV1DecisionsDecisionIdGetError {
    Status401(models::InlineObject5),
    Status403(models::InlineObject),
    Status404(models::InlineObject1),
    Status422(models::HttpValidationError),
    Status429(models::InlineObject4),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_decisions_v1_decisions_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListDecisionsV1DecisionsGetError {
    Status401(models::InlineObject5),
    Status403(models::InlineObject),
    Status404(models::InlineObject1),
    Status422(models::HttpValidationError),
    Status429(models::InlineObject4),
    UnknownValue(serde_json::Value),
}

/// One decision by id.  Requires the `decisions:read` scope. A decision you may not read — because it belongs to another project, another altitude, or is still mid-conversation — returns the same `404` as one that does not exist.  The URL is flat (no project component) because a decision id is globally unique. Authorization is still per project: the caller's altitude membership is resolved FIRST, then the row is loaded, its project resolved through the membership gate, and only then the altitude + state filters — every one of those failures producing the SAME 404 a nonexistent id gets, so this route is not an oracle for \"that decision exists but you may not see it\".  `403 no_altitude_membership` is the one refusal that is not a 404, and it is raised before any id is looked at, so it says nothing about the id.
pub async fn get_decision_v1_decisions_decision_id_get(
    configuration: &configuration::Configuration,
    params: GetDecisionV1DecisionsDecisionIdGetParams,
) -> Result<models::DecisionResponse, Error<GetDecisionV1DecisionsDecisionIdGetError>> {
    let uri_str = format!(
        "{}/v1/decisions/{decision_id}",
        configuration.base_path,
        decision_id = crate::apis::urlencode(params.decision_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DecisionResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DecisionResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetDecisionV1DecisionsDecisionIdGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// One page of a project's decisions, newest first.  Requires the `decisions:read` scope, which is **not** granted by default — mint a key that asks for it. Only settled states are served; `captured` and `interviewing` are mid-conversation and are never returned. Results are further limited to decisions owned by an altitude your account belongs to — a **relevance** filter, not a confidentiality boundary (altitude membership is self-service).  The `filters` block echoes what was actually applied, so an empty page is never ambiguous about which narrowing produced it.  Refusals beyond the standard envelopes:  * `403 no_altitude_membership` — your account belongs to no altitude,   so nothing here is readable. A statement about your account, not   about the project. * `422 owner_layer_not_permitted` — `owner_layer` asked outside your   membership. The filter can only narrow. * `422 state_not_readable` — `state` asked for a state this surface   does not serve.
pub async fn list_decisions_v1_decisions_get(
    configuration: &configuration::Configuration,
    params: ListDecisionsV1DecisionsGetParams,
) -> Result<models::DecisionsListResponse, Error<ListDecisionsV1DecisionsGetError>> {
    let uri_str = format!("{}/v1/decisions", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("project_id", &params.project_id.to_string())]);
    if let Some(ref param_value) = params.state {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("state".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "state",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref param_value) = params.owner_layer {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .into_iter()
                    .map(|p| ("owner_layer".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "owner_layer",
                &param_value
                    .into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DecisionsListResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DecisionsListResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListDecisionsV1DecisionsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
