/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`fetch_boundary_v1_graph_project_id_boundary_node_id_get`]
#[derive(Clone, Debug)]
pub struct FetchBoundaryV1GraphProjectIdBoundaryNodeIdGetParams {
    /// The project the boundary lives in.
    pub project_id: String,
    /// The boundary node to inspect.
    pub node_id: String
}

/// struct for passing parameters to the method [`fetch_graph_v1_graph_project_id_get`]
#[derive(Clone, Debug)]
pub struct FetchGraphV1GraphProjectIdGetParams {
    /// The project whose main-branch graph to fetch.
    pub project_id: String
}

/// struct for passing parameters to the method [`fetch_node_with_neighbors_v1_graph_project_id_node_node_id_get`]
#[derive(Clone, Debug)]
pub struct FetchNodeWithNeighborsV1GraphProjectIdNodeNodeIdGetParams {
    /// The project the node lives in.
    pub project_id: String,
    /// The node to fetch.
    pub node_id: String
}


/// struct for typed errors of method [`fetch_boundary_v1_graph_project_id_boundary_node_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchBoundaryV1GraphProjectIdBoundaryNodeIdGetError {
    Status401(models::InlineObject3),
    Status403(models::InlineObject),
    Status404(models::InlineObject1),
    Status422(models::HttpValidationError),
    Status429(models::InlineObject2),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_graph_v1_graph_project_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchGraphV1GraphProjectIdGetError {
    Status401(models::InlineObject3),
    Status403(models::InlineObject),
    Status404(models::InlineObject1),
    Status422(models::HttpValidationError),
    Status429(models::InlineObject2),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_node_with_neighbors_v1_graph_project_id_node_node_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchNodeWithNeighborsV1GraphProjectIdNodeNodeIdGetError {
    Status401(models::InlineObject3),
    Status403(models::InlineObject),
    Status404(models::InlineObject1),
    Status422(models::HttpValidationError),
    Status429(models::InlineObject2),
    UnknownValue(serde_json::Value),
}


/// Returns the boundary view for a single node: the inputs and outputs that cross the node's enforcement perimeter. Used by clients that visualize a node's contract surface in isolation from the rest of the graph.
pub async fn fetch_boundary_v1_graph_project_id_boundary_node_id_get(configuration: &configuration::Configuration, params: FetchBoundaryV1GraphProjectIdBoundaryNodeIdGetParams) -> Result<models::BoundaryResponse, Error<FetchBoundaryV1GraphProjectIdBoundaryNodeIdGetError>> {

    let uri_str = format!("{}/v1/graph/{project_id}/boundary/{node_id}", configuration.base_path, project_id=crate::apis::urlencode(params.project_id), node_id=crate::apis::urlencode(params.node_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BoundaryResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BoundaryResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchBoundaryV1GraphProjectIdBoundaryNodeIdGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns the active main-branch graph (nodes, ports, edges, version) for the project. Read-only: the main branch is merge-only. To make changes, fork a branch (`POST /v1/projects/{project_id}/branches`) and apply deltas to it.
pub async fn fetch_graph_v1_graph_project_id_get(configuration: &configuration::Configuration, params: FetchGraphV1GraphProjectIdGetParams) -> Result<models::GraphResponse, Error<FetchGraphV1GraphProjectIdGetError>> {

    let uri_str = format!("{}/v1/graph/{project_id}", configuration.base_path, project_id=crate::apis::urlencode(params.project_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GraphResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GraphResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchGraphV1GraphProjectIdGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a single node along with its directly connected neighbors and edges (the 1-hop topology). The node must belong to the project's active main branch.
pub async fn fetch_node_with_neighbors_v1_graph_project_id_node_node_id_get(configuration: &configuration::Configuration, params: FetchNodeWithNeighborsV1GraphProjectIdNodeNodeIdGetParams) -> Result<models::NodeNeighborhoodResponse, Error<FetchNodeWithNeighborsV1GraphProjectIdNodeNodeIdGetError>> {

    let uri_str = format!("{}/v1/graph/{project_id}/node/{node_id}", configuration.base_path, project_id=crate::apis::urlencode(params.project_id), node_id=crate::apis::urlencode(params.node_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NodeNeighborhoodResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NodeNeighborhoodResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchNodeWithNeighborsV1GraphProjectIdNodeNodeIdGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

