/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`healthz_v1_healthz_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum HealthzV1HealthzGetError {
    UnknownValue(serde_json::Value),
}


/// Returns `{\"ok\": true}` when the /v1/ surface is serving traffic. Unauthenticated. Use this for load-balancer and uptime-monitor checks; a 404 from this path means the /v1/ surface is disabled on the responding instance, not that the server is down.
pub async fn healthz_v1_healthz_get(configuration: &configuration::Configuration) -> Result<models::HealthzResponse, Error<HealthzV1HealthzGetError>> {

    let uri_str = format!("{}/v1/__healthz", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::HealthzResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::HealthzResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<HealthzV1HealthzGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

