/*
 * hydrate.sh v1 API
 *
 * The hydrate.sh public API. All routes are scoped to the `/v1/` prefix and require a Bearer API key (see Authentication).  **Stability:** `v1` is the wire-stable surface. Breaking changes will rebase to `/v2/`.
 *
 * The version of the OpenAPI document: 1.0.0-rc.1
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`list_projects_v1_projects_get`]
#[derive(Clone, Debug)]
pub struct ListProjectsV1ProjectsGetParams {
    /// Maximum projects to return. Defaults to 100; max 200.
    pub limit: Option<u32>
}


/// struct for typed errors of method [`list_projects_v1_projects_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListProjectsV1ProjectsGetError {
    Status401(models::InlineObject3),
    Status403(models::InlineObject),
    Status422(models::HttpValidationError),
    Status429(models::InlineObject2),
    UnknownValue(serde_json::Value),
}


/// Returns the projects the caller can see. For API-key callers the list is further filtered by the per-key project allowlist (if configured). Archived projects are excluded. An empty list is a normal response when the caller has no visible projects.
pub async fn list_projects_v1_projects_get(configuration: &configuration::Configuration, params: ListProjectsV1ProjectsGetParams) -> Result<models::ProjectsListResponse, Error<ListProjectsV1ProjectsGetError>> {

    let uri_str = format!("{}/v1/projects", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ProjectsListResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ProjectsListResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListProjectsV1ProjectsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

